---
- hosts: localhost
  gather_facts: False
  become: True
  become_method: sudo
  tasks:

  - name: create temperary dir
    file: path=/tmp/provision/{{item}} state=directory
    with_items:
      - bin
      - script

  - name: Download files for provision AWS
    get_url: 
      url: "{{ item }}"
      dest: /tmp/provision/script
    with_items:
      - http://www.opentlc.com/download/ansible_bootcamp/scripts/common.sh
      - http://www.opentlc.com/download/ansible_bootcamp/scripts/jq-linux64
      - http://www.opentlc.com/download/ansible_bootcamp/scripts/order_svc.sh

  - name: Change a shall scipit content
    replace:
      path: "/tmp/provision/script/{{ item }}"
      regexp: 'jq'
      replace: '/tmp/provision/bin/jq'
    with_items:
      - common.sh
      - order_svc.sh

  - name: Change file mode bits
    file:
      path: "/tmp/provision/script/{{ item }}"
      mode: u+x
    with_items:
      - jq-linux64
      - order_svc.sh

  - name: Move jq-linux64
    command: mv /tmp/provision/script/jq-linux64 /tmp/provision/bin/jq

  - name: Create credential.rc
    template:
      src: credential.rc.j2
      dest: /tmp/provision/script/credential.rc

  - name: Provision AWS instances
    shell: source /tmp/provision/script/credential.rc; /tmp/provision/script/order_svc.sh -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1 -y

  - name: Remove All files
    file:
      path: /tmp/provision
      state: absent
    ignore_errors: yes

  - name: Wait while provisioning AWS instances
    pause:
      minutes: 30
